name: Lint and Build
on:
  workflow_dispatch:
  push:
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: yarn
        run: yarn
      - name: yarn build
        run: yarn build
      - name: yarn lint
        run: yarn lint --max-warnings=0
